language: php

php:
  - '7.0'
  - '7.1'

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_script:
  - composer self-update
  - composer update

script:
  - bin/phpunit --coverage-clover=coverage.clover

notifications:
  email:
    - xgc1986@gmail.com

